### ISSUE TITLE
你好,请问项目的目录结构是否调整了

### ISSUE THREAD

**Issue by alanyao80** [wenjun1055/swoole-yaf#3]
实际代码里application/library/Base/Controllers,而你说明文档是写着application/Base/Controllers.php

另外能请教几个问题吗:
1. 你项目里没有.htaccess , 请问是不是在服务器其它地方配置了
2.根据你给的附件源码编译加载后, 其它旧的yaf项目无法运行,出现连接被重置的错误

我的环境是centos6.7 php5.5.34

**Comment by wenjun1055** [comment]
1、这里根本不需要.htaccess，swoole就做了server
2、你可以看看我都改了啥，我已经把yaf的源码改了，这个已经属于一个swoole的高度定制版，已经不能运行原来的程序

**Comment by alanyao80** [comment]
好的,明白了~
